global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Unified MemoryOS metrics endpoint
  - job_name: 'memoryos'
    static_configs:
      - targets: ['memoryos:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'memoryos-metrics'
    static_configs:
      - targets: ['memoryos:9090']
    metrics_path: '/v1/metrics'
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
