openapi: 3.1.0
info:
  title: MemoryOS Cognitive Trace Propagation v2
  description: |
    **Enhanced Cognitive Trace ID Propagation Contract**

    This contract defines enhanced cognitive trace ID propagation across APIs, events,
    and logs with improved correlation capabilities for the Memory-Centric Family AI system.

    **Cognitive Trace ID v2 Features:**
    - **Enhanced Correlation**: Improved trace correlation across family device boundaries
    - **Memory Context Preservation**: Maintains family memory context throughout trace lifecycle
    - **Family Intelligence Integration**: Traces include family relationship and emotional context
    - **Cross-Device Coordination**: Seamless trace propagation across family device ecosystem
    - **Privacy-Preserving**: Trace IDs respect family privacy and age-appropriate access controls
    - **Performance Optimized**: Efficient trace propagation with minimal overhead

    **Memory-Centric Integration:**
    - Traces correlate with family memory formation and recall operations
    - Cognitive processing steps maintain family relationship context
    - Memory sync operations preserve trace continuity across devices
    - Family intelligence insights are traceable to source cognitive operations

    **Family Context Enhancement:**
    - `family_memory_id`: Links traces to specific family memory instances
    - `relationship_context`: Active family relationships affecting cognitive processing
    - `emotional_context`: Family emotional state during cognitive operations
    - `memory_space`: Memory space classification (personal/shared/extended/interfamily)
    - `device_context`: Device-specific context for cross-device trace correlation

    **Architecture Integration:**
    - Central trace correlation service for family-wide cognitive operations
    - Integration with observability stack for family intelligence analytics
    - Memory backbone trace lifecycle management
    - Cross-plane trace propagation (Agent/Tool/Control planes)
  version: "2.0.0"
  contact:
    name: MemoryOS Platform Core Team
    url: https://familyos.local/support/platform
    email: platform-support@familyos.local
  license:
    name: Family OS Private License
    url: https://familyos.local/licenses/family-os

servers:
  - url: https://platform.familyos.local/tracing/v2
    description: Production Cognitive Trace Service
  - url: https://staging-platform.familyos.local/tracing/v2
    description: Staging Environment
  - url: http://localhost:8082/tracing/v2
    description: Local Development

security:
  - FamilyOSAuth: []
  - SystemAuth: []

paths:
  /traces:
    post:
      summary: Initialize Cognitive Trace
      description: |
        Initialize a new cognitive trace for family cognitive operations with enhanced context.

        **Memory-Centric Features:**
        - Automatic family context detection and embedding
        - Memory backbone integration for trace persistence
        - Cross-device trace coordination for family operations
      operationId: initializeCognitiveTrace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CognitiveTraceRequest'
      responses:
        '201':
          description: Cognitive trace initialized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitiveTraceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /traces/{traceId}:
    get:
      summary: Get Cognitive Trace Details
      description: |
        Retrieve detailed information about a specific cognitive trace including
        family context, memory correlations, and cross-device activities.
      operationId: getCognitiveTrace
      parameters:
        - name: traceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: Cognitive trace identifier (UUIDv7)
      responses:
        '200':
          description: Cognitive trace details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitiveTraceDetails'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

    patch:
      summary: Update Cognitive Trace Context
      description: |
        Update cognitive trace with additional family context, memory correlations,
        or cross-device activity information.
      operationId: updateCognitiveTrace
      parameters:
        - name: traceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CognitiveTraceUpdate'
      responses:
        '200':
          description: Cognitive trace updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitiveTraceResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'

  /traces/{traceId}/spans:
    post:
      summary: Add Cognitive Span
      description: |
        Add a new cognitive span to an existing trace with family context preservation.
      operationId: addCognitiveSpan
      parameters:
        - name: traceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CognitiveSpanRequest'
      responses:
        '201':
          description: Cognitive span added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitiveSpanResponse'

  /traces/family/{familyId}:
    get:
      summary: Get Family Cognitive Traces
      description: |
        Retrieve cognitive traces for a specific family with relationship context
        and cross-device correlation information.
      operationId: getFamilyCognitiveTraces
      parameters:
        - name: familyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: startTime
          in: query
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          schema:
            type: string
            format: date-time
        - name: memorySpace
          in: query
          schema:
            type: string
            enum: [personal, selective, shared, extended, interfamily]
      responses:
        '200':
          description: Family cognitive traces retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FamilyCognitiveTraces'

components:
  schemas:
    CognitiveTraceRequest:
      type: object
      required:
        - operation_type
        - family_context
      properties:
        operation_type:
          type: string
          enum: [memory_formation, memory_recall, attention_gating, working_memory, intelligence_advisory]
          description: Type of cognitive operation being traced
        family_context:
          $ref: '#/components/schemas/FamilyContext'
        memory_context:
          $ref: '#/components/schemas/MemoryContext'
        device_context:
          $ref: '#/components/schemas/DeviceContext'
        parent_trace_id:
          type: string
          format: uuid
          description: Parent trace ID for nested operations
        metadata:
          type: object
          additionalProperties: true
          description: Additional operation-specific metadata

    CognitiveTraceResponse:
      type: object
      required:
        - trace_id
        - status
        - created_at
      properties:
        trace_id:
          type: string
          format: uuid
          description: Unique cognitive trace identifier (UUIDv7)
        status:
          type: string
          enum: [active, completed, failed]
        created_at:
          type: string
          format: date-time
        family_context:
          $ref: '#/components/schemas/FamilyContext'
        correlation_ids:
          $ref: '#/components/schemas/CorrelationIds'

    CognitiveTraceDetails:
      allOf:
        - $ref: '#/components/schemas/CognitiveTraceResponse'
        - type: object
          properties:
            spans:
              type: array
              items:
                $ref: '#/components/schemas/CognitiveSpan'
            memory_operations:
              type: array
              items:
                $ref: '#/components/schemas/MemoryOperation'
            cross_device_activities:
              type: array
              items:
                $ref: '#/components/schemas/CrossDeviceActivity'
            performance_metrics:
              $ref: '#/components/schemas/PerformanceMetrics'

    CognitiveTraceUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [active, completed, failed]
        family_context:
          $ref: '#/components/schemas/FamilyContext'
        memory_context:
          $ref: '#/components/schemas/MemoryContext'
        additional_metadata:
          type: object
          additionalProperties: true

    CognitiveSpanRequest:
      type: object
      required:
        - span_name
        - operation_type
      properties:
        span_name:
          type: string
          description: Human-readable span name
        operation_type:
          type: string
          enum: [hippocampus_encoding, working_memory_admission, attention_gate_evaluation, intelligence_advisory]
        family_context:
          $ref: '#/components/schemas/FamilyContext'
        start_time:
          type: string
          format: date-time
        parent_span_id:
          type: string
          format: uuid

    CognitiveSpanResponse:
      type: object
      required:
        - span_id
        - trace_id
        - status
      properties:
        span_id:
          type: string
          format: uuid
        trace_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [active, completed, failed]
        created_at:
          type: string
          format: date-time

    CognitiveSpan:
      allOf:
        - $ref: '#/components/schemas/CognitiveSpanResponse'
        - type: object
          properties:
            span_name:
              type: string
            operation_type:
              type: string
            duration_ms:
              type: number
            family_context:
              $ref: '#/components/schemas/FamilyContext'
            memory_operations:
              type: array
              items:
                $ref: '#/components/schemas/MemoryOperation'

    FamilyContext:
      type: object
      required:
        - family_id
      properties:
        family_id:
          type: string
          format: uuid
          description: Family unit identifier
        family_member_id:
          type: string
          format: uuid
          description: Specific family member involved
        relationship_context:
          type: array
          items:
            type: string
          description: Active family relationships affecting operation
        emotional_context:
          $ref: '#/components/schemas/EmotionalContext'
        privacy_level:
          type: string
          enum: [personal, family_selective, family_shared, extended_family]

    MemoryContext:
      type: object
      properties:
        memory_space:
          type: string
          enum: [personal, selective, shared, extended, interfamily]
        memory_type:
          type: string
          enum: [episodic, semantic, procedural, working]
        family_memory_id:
          type: string
          format: uuid
          description: Related family memory instance
        consolidation_stage:
          type: string
          enum: [encoding, consolidation, retrieval]

    DeviceContext:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
        device_type:
          type: string
          enum: [mobile, desktop, tablet, wearable, smart_home]
        sync_status:
          type: string
          enum: [local_only, syncing, synced, offline]
        cross_device_session:
          type: string
          format: uuid
          description: Session spanning multiple devices

    EmotionalContext:
      type: object
      properties:
        emotional_state:
          type: string
          enum: [positive, neutral, negative, mixed]
        emotional_intensity:
          type: number
          minimum: 0
          maximum: 1
        family_emotional_climate:
          type: string
          enum: [harmonious, neutral, tense, celebratory]

    CorrelationIds:
      type: object
      properties:
        request_id:
          type: string
          format: uuid
        session_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        device_id:
          type: string
          format: uuid
        family_id:
          type: string
          format: uuid

    MemoryOperation:
      type: object
      properties:
        operation_id:
          type: string
          format: uuid
        operation_type:
          type: string
          enum: [store, retrieve, update, delete, sync]
        memory_type:
          type: string
          enum: [episodic, semantic, procedural, working]
        duration_ms:
          type: number
        success:
          type: boolean

    CrossDeviceActivity:
      type: object
      properties:
        activity_id:
          type: string
          format: uuid
        source_device_id:
          type: string
          format: uuid
        target_device_id:
          type: string
          format: uuid
        activity_type:
          type: string
          enum: [handoff, sync, backup, restore]
        duration_ms:
          type: number

    PerformanceMetrics:
      type: object
      properties:
        total_duration_ms:
          type: number
        memory_operations_count:
          type: number
        cross_device_activities_count:
          type: number
        error_count:
          type: number
        p95_latency_ms:
          type: number

    FamilyCognitiveTraces:
      type: object
      properties:
        family_id:
          type: string
          format: uuid
        total_traces:
          type: number
        traces:
          type: array
          items:
            $ref: '#/components/schemas/CognitiveTraceDetails'
        aggregated_metrics:
          $ref: '#/components/schemas/PerformanceMetrics'

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    FamilyOSAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.familyos.local/oauth/authorize
          tokenUrl: https://auth.familyos.local/oauth/token
          scopes:
            trace:read: Read cognitive trace information
            trace:write: Create and update cognitive traces
            family:trace:read: Read family-wide cognitive traces

    SystemAuth:
      type: http
      scheme: bearer
      description: System-to-system authentication for internal services
